### ISSUE TITLE
docker方式部署如何修改Web服务端口

### ISSUE THREAD

**Issue by conghua1013** [flagify-com/OctoMation#10]
## docker部署方式如何修改Web服务端口号

**Comment by mmaoyu** [comment]
1. 修改/etc/profile.d/sp_deploy.sh 中的443为您希望的端口
`export S9E_HTTPS_PORT="443"`

2. 生效环境变量
` source /etc/profile`

3. 确认端口是否需改成功
`echo ${S9E_HTTPS_PORT}`

4. 重启shakespeare-static服务
`docker ps -a|grep shakespeare-static|awk '{print $1}'|xargs docker rm -f`
`docker-compose -f /opt/shakespeare/docker-compose.yml up -d shakespeare-static`

5. 确认服务端口已修改，
`docker-compose -f /opt/shakespeare/docker-compose.yml ps |grep shakespeare-static`

6. 在浏览器中使用新的端口访问
   `https://xx.xx.xx.xx:port`
