### ISSUE TITLE
ERROR! backup error! used_count:87  too high,greater than 80

### ISSUE THREAD

**Issue by godway111** [flagify-com/OctoMation#101]
![image](https://github.com/flagify-com/OctoMation/assets/103880643/d8ed7fe9-03a3-42ad-86de-0e9ff1e5ff82)

**Comment by wuzhi-dev** [comment]
1.检查tmp目录，看是否可以清理空间出来
2.执行安装脚本时可以加上参数-b 0 不备份
3. 安装脚本可以加上参数-d 目录名  解压到其他目录执行

**Comment by godway111** [comment]
> 1.检查tmp目录，看是否可以清理空间出来 2.执行安装脚本时可以加上参数-b 0 不备份 3. 安装脚本可以加上参数-d 目录名 解压到其他目录执行

执行`./octomation_install.sh -m 3 -i /data/sec/docker/docker -b 0 -d /data/data/OctoMation`
报错：
![image](https://github.com/flagify-com/OctoMation/assets/103880643/79602549-b32e-44e7-ab50-68214ce60972)
请问这个怎么解决

**Comment by wuzhi-dev** [comment]
换安装目录了  看这个  https://github.com/flagify-com/OctoMation/wiki/OctoMation%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C#opt%E6%89%80%E5%9C%A8%E5%88%86%E5%8C%BA%E7%A9%BA%E9%97%B4%E4%B8%8D%E5%A4%9F%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AE%89%E8%A3%85%E7%9B%AE%E5%BD%95

**Comment by godway111** [comment]
> 换安装目录了 看这个 https://github.com/flagify-com/OctoMation/wiki/OctoMation%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C#opt%E6%89%80%E5%9C%A8%E5%88%86%E5%8C%BA%E7%A9%BA%E9%97%B4%E4%B8%8D%E5%A4%9F%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AE%89%E8%A3%85%E7%9B%AE%E5%BD%95

这个我看了，也指定了安装目录，解决不了。

**Comment by wuzhi-dev** [comment]
docker的存储路径改了吗？如果按wiki改的，看下这个https://github.com/flagify-com/OctoMation/wiki/OctoMation%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C#%E6%97%A0%E6%98%8E%E7%A1%AE%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF%E7%9B%B4%E6%8E%A5%E6%98%BE%E7%A4%BA%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5
不能解决的话 麻烦项目首页添加小助手，加入到群里，我们远程看下

**Comment by wuzhi-dev** [comment]
@godway111  老师 后续安装有进展吗

**Comment by godway111** [comment]
@wuzhi-dev 装的，麻烦协助看下什么问题

**Comment by godway111** [comment]
> @godway111 老师 后续安装有进展吗

我添加助手微信了

**Comment by wuzhi-dev** [comment]
> > @godway111 老师 后续安装有进展吗
> 
> 我添加助手微信了

好的  稍后到群里后@一下群主  我们安排远程协助 谢谢

**Comment by wuzhi-dev** [comment]
已解决，由于source /etc/profile出错导致的退出
