### ISSUE TITLE
规则节点判断失败

### ISSUE THREAD

**Issue by godway111** [flagify-com/OctoMation#110]
![image](https://github.com/flagify-com/OctoMation/assets/103880643/0b31adaa-aaca-44ab-959d-e307e215f64b)

**Comment by wuzhi-dev** [comment]
规则生成的name重名导致，如遇到该问题可以删除规则重建即可。
将在下个版本修复。

**Comment by wuzhi-dev** [comment]
已在1.1.2版本修复
