### ISSUE TITLE
网页全屏时，无法下拉选择应用

### ISSUE THREAD

**Issue by godway111** [flagify-com/OctoMation#114]
进入作战室，浏览器网页全屏状态下，无法使用鼠标滚动/下拉选择应用

**Comment by godway111** [comment]
全屏状态：
![image](https://github.com/flagify-com/OctoMation/assets/103880643/22266f3c-d690-4b80-b707-f4d3591c03ed)
非全屏状态
![image](https://github.com/flagify-com/OctoMation/assets/103880643/8b9182d4-3e29-46d1-80da-aea6940ec404)
windows 10 ，chrome版本 121.0.6167.185（正式版本） （64 位）

**Comment by wuzhi-dev** [comment]
确认问题存在，后续修复
