### ISSUE TITLE
安装时报错 

### ISSUE THREAD

**Issue by alohajerrys** [flagify-com/OctoMation#123]
![image](https://github.com/flagify-com/OctoMation/assets/33277616/5f087c63-634d-4825-9db3-fe1c13f8584a)
![image](https://github.com/flagify-com/OctoMation/assets/33277616/d026a0db-dcce-4105-ba55-3805f6700ba4)
![image](https://github.com/flagify-com/OctoMation/assets/33277616/706442c8-f342-402d-bed8-fa4d74222962)
![image](https://github.com/flagify-com/OctoMation/assets/33277616/df5470a5-5177-4062-99a4-952ac3c721ea)

执行到一半
系统会报错 SSH会断开  尝试多次重装系统和检查环境仍然无效 
系统负载很高，但是 CPU 和内存都没有占用多少

**Comment by wuzhi-dev** [comment]
![image](https://github.com/flagify-com/OctoMation/assets/148321736/c287d2cb-65ef-436e-9be2-4703bd48d21a)
从日志上看 可能是宿主机的cpu有问题
换一台机器看看

**Comment by alohajerrys** [comment]
> ![image](https://private-user-images.githubusercontent.com/148321736/330399864-c287d2cb-65ef-436e-9be2-4703bd48d21a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTQxNjAsIm5iZiI6MTcxNTkxMzg2MCwicGF0aCI6Ii8xNDgzMjE3MzYvMzMwMzk5ODY0LWMyODdkMmNiLTY1ZWYtNDM2ZS05YmUyLTQ3MDNiZDQ4ZDIxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMjQ0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzlmNzQ3NjgxMmQxYzBlNzQ1YmIzYmFiNzBkZDJlNWU1ZWFiOGYwYjkyMTYxMmUzYTg5MmY0NWYzM2Y0ZTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l7Kdm78i-7ni75yD5vlqwTdepWjzdoc89AtzxVk_nW4) 从日志上看 可能是宿主机的cpu有问题 换一台机器看看

已解决，分配的vcpus超过物理cpu cores或者其他宿主机占用过多导致，重新分配了较低的vcpus就正常安装了  感谢支持
