### ISSUE TITLE
求助 多次安装失败

### ISSUE THREAD

**Issue by kuailefengnan777** [flagify-com/OctoMation#126]
![image](https://github.com/flagify-com/OctoMation/assets/59561439/5dc5482a-e366-4fd7-95a1-1676c2279da1)

腾讯云OpenCloudOS release 8.8.2305 (Core) 

./octomation_community_docker_install_offline_1.1.2.sh 
离线：Docker version 26.xx     docker-compose version 1.29.2
在线自动安装：Docker version 20.10.12     docker-compose version 1.29.2
都安装失败

**Comment by wuzhi-dev** [comment]
systemctl restart docke，然后尝试重新安装

**Comment by kuailefengnan777** [comment]
尝试过了，还是不行

**Comment by wuzhi-dev** [comment]
![image](https://github.com/flagify-com/OctoMation/assets/148321736/f6342b10-5e7c-4fee-9368-705347456fa5)
麻烦添加微信小助手 加到企业微信群里 远程协助看下原因

**Comment by wuzhi-dev** [comment]
机器内存不足导致
