### ISSUE TITLE
建议初始化一个默认事件类型

### ISSUE THREAD

**Issue by wzfukui** [flagify-com/OctoMation#16]
首次登录系统，想使用作战室创建事件，发现没有可选的事件类型。

<img width="986" alt="image" src="https://github.com/flagify-com/OctoMation/assets/146505187/97cec711-6d3f-496e-bd7c-9e649b9d00a8">

建议初始化一个默认事件类型。

**Comment by wuzhi-dev** [comment]
将会在下个版本增加
