### ISSUE TITLE
剧本画布是否支持连线循环？

### ISSUE THREAD

**Issue by wzfukui** [flagify-com/OctoMation#24]
![wecom-temp-27184-8109dc26472d8493433c7a921fe4d229](https://github.com/flagify-com/OctoMation/assets/146505187/aa937171-ed49-4e9b-8edd-2256182112bc)

比如这样的需求。

**Comment by wuzhi-dev** [comment]
考虑到剧本设计和实现的复杂度，以及后期运行维护和诊断的难度，暂不支持。
编排流程是个有向无环图 不回头的 需要回头的逻辑建议走分支后面处理 。
