### ISSUE TITLE
基础数据里的通用字段不能直接删除，是处于什么考虑？

### ISSUE THREAD

**Issue by uf1y** [flagify-com/OctoMation#26]
为什么基础数据里的通用字段不提供修改和删除功能？我想肯定有一些理由吧，但是产品界面上也没看到任何提示，这个有什么道道？

**Comment by wuzhi-dev** [comment]
不是不能删，是删除后有潜在风险。为了提升已经编排剧本的执行效率，增强系统可靠性，并在未来自持分布式模式下本地规则判断，OctoOmation剧本编排对剧本的节点和关键逻辑做了预处理，在剧本发布的过程中，会对通用字段、节点参数、判断规则进行预编译。如果此后用户删除或者修改了通用字段，那么会导致之前的一些剧本或节点无法执行。

当然，技术上在数据库里肯定可以删除的，包括软删除，如果一个字段从未被引用删除了也不会有很大影响，但这要求产品自身支持在大量的剧本中搜索字段的引用关系，非常复杂，因此暂时未考虑实现。未来会使用更合适的方式帮助用户更方便地管理和维护基础数据。
