### ISSUE TITLE
求助：离线安装失败

### ISSUE THREAD

**Issue by lifangning** [flagify-com/OctoMation#47]
主机，按安装文档的要求配置：
![image](https://github.com/flagify-com/OctoMation/assets/7867490/9ffb4b02-ea9a-4fd8-b2d8-ea04a4f93b03)

安装时间大约二十多分钟，最终报以下错误：
![企业微信截图_16980239646828](https://github.com/flagify-com/OctoMation/assets/7867490/d1620878-3b10-49b1-9157-03776cec3538)

请大拿们帮忙出出主意！！

**Comment by wuzhi-dev** [comment]
> 主机，按安装文档的要求配置： ![image](https://user-images.githubusercontent.com/7867490/277541648-9ffb4b02-ea9a-4fd8-b2d8-ea04a4f93b03.png)
> 
> 安装时间大约二十多分钟，最终报以下错误： ![企业微信截图_16980239646828](https://user-images.githubusercontent.com/7867490/277542166-d1620878-3b10-49b1-9157-03776cec3538.png)
> 
> 请大拿们帮忙出出主意！！

**Comment by Duanexiao** [comment]
@lifangning 请问你这边是用的离线安装包还是在线安装包?

**Comment by wuzhi-dev** [comment]
@lifangning 具体的部署环境可以描述一下嘛？是windows下的vmware虚拟机安装的linux吗？

**Comment by lifangning** [comment]
阿里云盘下载的离线安装包。
是使用 KVM 虚拟的主机。

**Comment by Duanexiao** [comment]
> 阿里云盘下载的离线安装包。 是使用 KVM 虚拟的主机。
> 
> 安装了两遍，报相同的错误。

可以试试在线安装包

**Comment by wuzhi-dev** [comment]
cmu的问题，我们想办法复现一下。

**Comment by wuzhi-dev** [comment]
@lifangning 请问您宿主机KVM软件的品牌是什么，宿主机是PC电脑还是硬件服务器，给虚拟机的硬件配置信息是什么？

**Comment by wuzhi-dev** [comment]
@lifangning 更新了一版离线安装包，麻烦更新安装，谢谢

**Comment by lifangning** [comment]
> @lifangning 更新了一版离线安装包，麻烦更新安装，谢谢

收到，多谢。请问下是否可以直接重新安装？还是需要清理环境？
另外，KVM 使用 Ubuntu 22.04 自带的版本（qemu-kvm）。

**Comment by wuzhi-dev** [comment]
> > @lifangning 更新了一版离线安装包，麻烦更新安装，谢谢
> 
> 收到，多谢。请问下是否可以直接重新安装？还是需要清理环境？ 另外，KVM 使用 Ubuntu 22.04 自带的版本（qemu-kvm）。

直接重新安装即可，如果磁盘空间不够可以清理一部分temp目录内容。
感谢反馈，也可以加入到交流群中交流讨论。

**Comment by lifangning** [comment]
已安装成功，多谢：
![企业微信截图_1698130042734](https://github.com/flagify-com/OctoMation/assets/7867490/808f8216-0b38-482b-b3f4-8254fce28651)
