### ISSUE TITLE
在事件接入配置中怎么指定从kafka的哪个主题中获取消息？

### ISSUE THREAD

**Issue by younger4fun** [flagify-com/OctoMation#53]
填写好消息队列例如xxx_topic后，以测试接入按钮点击测试连通性，一直提示无消息，实际上该主题已经发送过消息。

**Comment by wuzhi-dev** [comment]
你好！感谢关注和使用。请参考安装部署手册中的[我的第一个OctoMation-事件接入](https://github.com/flagify-com/OctoMation/wiki/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AAOctoMation-%E4%BA%8B%E4%BB%B6%E6%8E%A5%E5%85%A5)进行配置。

另外，建议在测试连通性的时候，在Kafka服务器上看下端口连接情况，确认OctoMation与Kafka服务器建立了TCP连接。
