### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by qqdan3** [flagify-com/OctoMation#67]
安装了3次，均报错，然后在这个位置卡了好久，不知道是什么原因。
系统是CENTOS 8， 有卡巴斯基防病毒软件。
磁盘空间40G，内存4G。
以上，谢谢。
![微信图片_20231113151836](https://github.com/flagify-com/OctoMation/assets/72116692/2ddbd507-ddfb-486d-b543-18e224a43c39)

**Comment by qqdan3** [comment]
![1](https://github.com/flagify-com/OctoMation/assets/72116692/022c4690-c014-40ce-bd57-0af9911565ff)

**Comment by williamdeve** [comment]
请参考系统部署文档：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2%E6%89%8B%E5%86%8C#%E7%A1%AC%E4%BB%B6%E8%A6%81%E6%B1%82

[硬件要求]
CPU：4核+
指令架构：X86_64
内存：8GB+
硬盘：200GB+ （默认安装在Linux系统的/opt目录），建议配置足够的空间，方便系统运行后存储数据和日志。

**Comment by qqdan3** [comment]
我只是想做个测试，跑个剧本，这些资源和硬件就要求这麽高么？

**Comment by williamdeve** [comment]
这是一个完整功能的编排和自动化产品，部署上就可以直接使用自动化能力的，因此在资源上有些要求。

**Comment by wzfukui** [comment]
> 我只是想做个测试，跑个剧本，这些资源和硬件就要求这麽高么？

可以参考这几个安装成功的配置：https://github.com/orgs/flagify-com/discussions/20
有人80G存储就安装成功了。

下一个版本会降低对磁盘空间的强制要求，让大家能更容易部署。

**Comment by qqdan3** [comment]
您好
 我调整了磁盘空间，最后还是报错了，请问这个要怎么改参数，谢谢
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月13日(星期一) 18:08
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
这是一个完整功能的编排和自动化产品，部署上就可以直接使用自动化能力的，因此在资源上有些要求。

**Comment by williamdeve** [comment]
你好，看看把内存调整到8g看下，如果还是不行，我们再远程

**Comment by qqdan3** [comment]
好的，我试试，谢谢
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月15日(星期三) 16:32
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
你好，看看把内存调整到8g看下，如果还是不行，我们再远程

**Comment by qqdan3** [comment]
您好
 程序安装完了，因为字符集没处理好，好像有点乱码未能解决。但是现在的问题是看不到访问页面，能给我一些命令，我自查下，是否安全OK，并且服务OK么？
谢谢
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月15日(星期三) 16:32
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
你好，看看把内存调整到8g看下，如果还是不行，我们再远程

**Comment by williamdeve** [comment]
这是运维手册：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E8%BF%90%E7%BB%B4%E6%89%8B%E5%86%8C
麻烦您检查几项：
1.容器中服务是否是启动的
2.网络是否是通的（虚拟机安装的话如果是nat模式需要映射）

**Comment by qqdan3** [comment]
您好 
 我尝试关闭了系统中第三方的防病毒后，就可以访问了，谢谢。
 另外，我想收集CVE的公告，目前看只有Redhat，我想收集nist或者github上的一些信息，如何添加？ 另外，我怎么绑定钉钉呢？ 
 谢谢
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月16日(星期四) 15:16
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
这是运维手册：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E8%BF%90%E7%BB%B4%E6%89%8B%E5%86%8C <https://github.com/flagify-com/OctoMation/wiki/OctoMation%E8%BF%90%E7%BB%B4%E6%89%8B%E5%86%8C >
 麻烦您检查几项：
 1.容器中服务是否是启动的
 2.网络是否是通的（虚拟机安装的话如果是nat模式需要映射）

**Comment by williamdeve** [comment]
https://github.com/flagify-com/OctoMationApps/releases/tag/APP  这里有钉钉的应用，通过应用管理上传到系统后配置资源就可以使用了。其他的需要要开发应用的话可以参考应用开发文档：https://github.com/flagify-com/OctoMation/wiki/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AAOctoMation-%E5%BA%94%E7%94%A8APP%E5%BC%80%E5%8F%91

**Comment by qqdan3** [comment]
收到，感谢您的回复。
我想再问下，现在的CVE获取的ZIP，是获取哪里的？ 
另外，我已经下载CVE的ZIP，并设定了钉钉，放到定期任务中。但是现在还没有信息出来，可能是现在没有新的CVE，我想问下，如果有搜索到的，会在哪里显示呢？
这个产品有详细的使用说明么？ 我技术不太行，所以想看看如何设定，担心设定错我。
以上，谢谢
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月16日(星期四) 15:52
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
https://github.com/flagify-com/OctoMationApps/releases/tag/APP <https://github.com/flagify-com/OctoMationApps/releases/tag/APP > 这里有钉钉的应用，通过应用管理上传到系统后配置资源就可以使用了。其他的需要要开发应用的话可以参考应用开发文档：https://github.com/flagify-com/OctoMation/wiki/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AAOctoMation-%E5%BA%94%E7%94%A8APP%E5%BC%80%E5%8F%91 <https://github.com/flagify-com/OctoMation/wiki/%E6%88%91%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AAOctoMation-%E5%BA%94%E7%94%A8APP%E5%BC%80%E5%8F%91 >

**Comment by williamdeve** [comment]
可以查看定时任务的执行结果，结果里执行的动作或者剧本上会有显示。
这是用户手册，请参考：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C

**Comment by qqdan3** [comment]
老师 您好
 谢谢您给的消息。
 实在是抱歉，我不懂编程，所以只能做一些简单的程序部署，所以到逻辑和剧本这块就很坎坷了，还请您见谅。
 我现在有3个问题 ：
 1、我做了一个CVE的剧本，在github下的，，然后钉钉也做好配置，但是这个有信息后首先是空的，只有链接，或许是没有检索到我要的信息，再有就是没有能推送到钉钉。需要哪里在匹配下么？
 2、我想增加github\cnnvd的漏洞库检测，这个要怎么去做呢？ 有没有剧本可以实现?
 3、我看您介绍资料的例子里还有fortinet的防火墙，这个是用来做啥的？ 这个工具可以被下载到么？
以上，这个编排对我来说却是有点难，还请见谅，也请多指教，谢谢。
------------------------------------------------------------------
发件人：狗哥 ***@***.***>
发送时间：2023年11月16日(星期四) 17:18
收件人：flagify-com/OctoMation ***@***.***>
抄　送：qqdan3 ***@***.***>; Author ***@***.***>
主　题：Re: [flagify-com/OctoMation] 安装时报错 (Issue #67)
可以查看定时任务的执行结果，结果里执行的动作或者剧本上会有显示。
 这是用户手册，请参考：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C <https://github.com/flagify-com/OctoMation/wiki/OctoMation%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C >

**Comment by wzfukui** [comment]
@qqdan3 你好，请移步到Discussion区，描述一下您的思路。我们会指导和演示如何完成这一需求。
