### ISSUE TITLE
: cannot remove '/opt/shakespeare/': Directory not empty

### ISSUE THREAD

**Issue by wuzhi-dev** [flagify-com/OctoMation#70]
: cannot remove '/opt/shakespeare/': Directory not empty

**Comment by wzfukui** [comment]
<img width="598" alt="image" src="https://github.com/flagify-com/OctoMation/assets/146505187/3071bf19-4cf6-4691-856d-e63f492838d7">

```
Failed to stop nginx.service: Unit nginx.service not loaded
rm: cannot remove '/opt/shakespeare/': Directory not empty
please exit shell for reinstall[如有需要请务必退出终端后再安装====
```

<img width="224" alt="image" src="https://github.com/flagify-com/OctoMation/assets/146505187/0f7499b4-4c0f-4b4c-9393-fe932fe35214">

**Comment by wzfukui** [comment]
从删除日志看，服务都已经清理完成了，目录删除失败。
请确认操作系统是否做过加固或者rm重定义， 建议看下别名配置，执行：alias
或者手工删除`rm -rf /opt/shakespeare`

**Comment by xiaoyugo61** [comment]
在线版安装后卸载问题，请使用
