### ISSUE TITLE
没有找到netmiko的模块

### ISSUE THREAD

**Issue by hughsky** [flagify-com/OctoMation#74]
HI
我在系统层面pip install netmiko 已经成功
但是在新建应用那边，import netmiko 报错提示
from netmiko import ConnectHandler\\nModuleNotFoundError: No module named \\'netmiko\\
这个netmiko需要在那个层面去安装

**Comment by wuzhi-dev** [comment]
> HI 我在系统层面pip install netmiko 已经成功 但是在新建应用那边，import netmiko 报错提示 from netmiko import ConnectHandler\nModuleNotFoundError: No module named \'netmiko\ 这个netmiko需要在那个层面去安装

参考：OctoMation中使用第三方Python模块 https://github.com/flagify-com/OctoMation/wiki/OctoMation%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%AC%AC%E4%B8%89%E6%96%B9Python%E6%A8%A1%E5%9D%97

**Comment by hughsky** [comment]
感谢回复，已经成功。

**Comment by wuzhi-dev** [comment]
1）在执行引擎的docker中安装，参考Discussion：[请问如何安装自定义的Python组件？ #27](https://github.com/orgs/flagify-com/discussions/27)
2）安装后，立即在执行引擎中执行Python，尝试import
3）如果能够成功import，说明已经成功安装，执行引擎调用应用APP时就可以正常执行。

**Comment by wuzhi-dev** [comment]
> 感谢回复，已经成功。

欢迎加入交流群 继续交流使用心得
