### ISSUE TITLE
Logstash案例有没有

### ISSUE THREAD

**Issue by hughsky** [flagify-com/OctoMation#79]
HI
我这配置有ELK，logstash 推送到ES
但是怎么推送到octomation呢，有没有案例。

**Comment by wuzhi-dev** [comment]
由Logstash完成事件的转发，发送到OctoMation自带的Kafka消息队列（推荐用户自备Kafka消息队列）
参考：https://github.com/flagify-com/OctoMation/wiki/OctoMation%E7%94%A8%E6%88%B7%E6%89%8B%E5%86%8C#3%E3%80%81%E4%BA%8B%E4%BB%B6%E6%8E%A5%E5%85%A5
