### ISSUE TITLE
问题：Pulling shakespeare-java-exe-python missed

### ISSUE THREAD

**Issue by Lu-manX2** [flagify-com/OctoMation#81]
Pulling shakespeare-java-exe-python (shakespeare-java-exe-python:1.0.0_community)...
The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by wuzhi-dev** [comment]
之前是已经pull过镜像了吗？

**Comment by Lu-manX2** [comment]
是一直没有pull下来的意思吧…这个镜像源在哪？

**Comment by wuzhi-dev** [comment]
https://hub.docker.com/search?q=wuzhizhineng 搜索镜像

**Comment by Lu-manX2** [comment]
Continue with the new image? [yN]y
Pulling shakespeare-java-exe-python (shakespeare-java-exe-python:1.0.0_community)...
pull access denied for shakespeare-java-exe-python, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 script: /tmp/honeyguide_whole_package/ai_package_to_deploy_1.0.0/ai_package_to_deploy/ai_install.sh, line: 994, 启动docker python执行引擎失败 
 当前目录: /tmp/honeyguide_whole_package/ai_package_to_deploy_1.0.0/ai_package_to_deploy, ai_install.sh 脚本执行失败 
 OctoMation 安装失败

**Comment by Lu-manX2** [comment]
docker pull shakespeare-java-exe-python
Using default tag: latest
Error response from daemon: pull access denied for shakespeare-java-exe-python, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by wuzhi-dev** [comment]
> docker pull shakespeare-java-exe-python Using default tag: latest Error response from daemon: pull access denied for shakespeare-java-exe-python, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

使用docker pull wuzhizhineng/shakespeare-java-exe-python:1.0.0_community 试试

**Comment by Lu-manX2** [comment]
这个单独执行可以，但是就算提前pull这个镜像还是会报这个错。

**Comment by wzxiaojf** [comment]
> 这个单独执行可以，但是就算提前pull这个镜像还是会报这个错。

先用离线包安装一下，在线版的我们内部再找新环境测试一下

**Comment by wuzhi-dev** [comment]
> Continue with the new image? [yN]y Pulling shakespeare-java-exe-python (shakespeare-java-exe-python:1.0.0_community)... pull access denied for shakespeare-java-exe-python, repository does not exist or may require 'docker login': denied: requested access to the resource is denied script: /tmp/honeyguide_whole_package/ai_package_to_deploy_1.0.0/ai_package_to_deploy/ai_install.sh, line: 994, 启动docker python执行引擎失败 当前目录: /tmp/honeyguide_whole_package/ai_package_to_deploy_1.0.0/ai_package_to_deploy, ai_install.sh 脚本执行失败 OctoMation 安装失败

感谢老师反馈，已经更新了镜像地址，麻烦下载新的在线安装包安装，非常感谢。
