### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Belee05** [flagify-com/OctoMation#97]
centos7.9使用在线安装还是离线安装，都失败，但报错信息中没有提示哪里有问题。服务器符合安装环境要求
` SUCCESS! backup hg finished
shakespeare install error,exit
 OctoMation 安装失败`
![image](https://github.com/flagify-com/OctoMation/assets/51012725/6622cb6b-33fd-4ae6-84ee-ded426e34d34)

**Comment by wuzhi-dev** [comment]
> centos7.9使用在线安装还是离线安装，都失败，但报错信息中没有提示哪里有问题。符合安装环境要求 ` SUCCESS! backup hg finished shakespeare install error,exit OctoMation 安装失败` ![image](https://private-user-images.githubusercontent.com/51012725/294408669-6622cb6b-33fd-4ae6-84ee-ded426e34d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU3NDMsIm5iZiI6MTcwNDQzNTQ0MywicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MDg2NjktNjYyMmNiNmItMzNmZC00YWU2LTg0ZWUtZGVkNDI2ZTM0ZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODE3M2U4ZmJlMTZlOWIyZTEyNmJiYWU1ZTQzZDI4M2ZjZmYzNTBjMDYyZGIyOGYzYjA0YjU4ZWYzYTVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zycAhA8nJHPM0ZW2W0XFx5h5fPRO-CBMHrwRdsypPts)

具体的内存信息 磁盘目录信息能麻烦发一下

**Comment by Belee05** [comment]
> > centos7.9使用在线安装还是离线安装，都失败，但报错信息中没有提示哪里有问题。符合安装环境要求 ` SUCCESS! backup hg finished shakespeare install error,exit OctoMation 安装失败` ![image](https://private-user-images.githubusercontent.com/51012725/294408669-6622cb6b-33fd-4ae6-84ee-ded426e34d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU3NDMsIm5iZiI6MTcwNDQzNTQ0MywicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MDg2NjktNjYyMmNiNmItMzNmZC00YWU2LTg0ZWUtZGVkNDI2ZTM0ZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODE3M2U4ZmJlMTZlOWIyZTEyNmJiYWU1ZTQzZDI4M2ZjZmYzNTBjMDYyZGIyOGYzYjA0YjU4ZWYzYTVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zycAhA8nJHPM0ZW2W0XFx5h5fPRO-CBMHrwRdsypPts)
> 
> 具体的内存信息 磁盘目录信息能麻烦发一下

![image](https://github.com/flagify-com/OctoMation/assets/51012725/15df4356-d133-4819-81d1-94317cbc2db7)

**Comment by wuzhi-dev** [comment]
> > > centos7.9使用在线安装还是离线安装，都失败，但报错信息中没有提示哪里有问题。符合安装环境要求 ` SUCCESS! backup hg finished shakespeare install error,exit OctoMation 安装失败` ![image](https://private-user-images.githubusercontent.com/51012725/294408669-6622cb6b-33fd-4ae6-84ee-ded426e34d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU3NDMsIm5iZiI6MTcwNDQzNTQ0MywicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MDg2NjktNjYyMmNiNmItMzNmZC00YWU2LTg0ZWUtZGVkNDI2ZTM0ZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODE3M2U4ZmJlMTZlOWIyZTEyNmJiYWU1ZTQzZDI4M2ZjZmYzNTBjMDYyZGIyOGYzYjA0YjU4ZWYzYTVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zycAhA8nJHPM0ZW2W0XFx5h5fPRO-CBMHrwRdsypPts)
> > 
> > 
> > 具体的内存信息 磁盘目录信息能麻烦发一下
> 
> ![image](https://private-user-images.githubusercontent.com/51012725/294411515-15df4356-d133-4819-81d1-94317cbc2db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzY2NDQsIm5iZiI6MTcwNDQzNjM0NCwicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MTE1MTUtMTVkZjQzNTYtZDEzMy00ODE5LTgxZDEtOTQzMTdjYmMyZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWY2N2M2NWNmY2ZjNzVjMjE5ZTc3NjY0ZWY0YTNiZWEzYzFmZTQ5MGI0ZWU0NWQ0Njc4NjcxM2QzYTc5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.75L7v_YA24jq6BH7ocyUYT1LVh_c2xIQ5jEmGN9_GwQ)

麻烦看下tmp和opt目录的使用情况，如果剩余空间比较小，建议清理掉一部分。安装时参数加上-b 0 不备份

**Comment by Belee05** [comment]
> > > > centos7.9使用在线安装还是离线安装，都失败，但报错信息中没有提示哪里有问题。符合安装环境要求 ` SUCCESS! backup hg finished shakespeare install error,exit OctoMation 安装失败` ![image](https://private-user-images.githubusercontent.com/51012725/294408669-6622cb6b-33fd-4ae6-84ee-ded426e34d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzU3NDMsIm5iZiI6MTcwNDQzNTQ0MywicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MDg2NjktNjYyMmNiNmItMzNmZC00YWU2LTg0ZWUtZGVkNDI2ZTM0ZDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODE3M2U4ZmJlMTZlOWIyZTEyNmJiYWU1ZTQzZDI4M2ZjZmYzNTBjMDYyZGIyOGYzYjA0YjU4ZWYzYTVhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zycAhA8nJHPM0ZW2W0XFx5h5fPRO-CBMHrwRdsypPts)
> > > 
> > > 
> > > 具体的内存信息 磁盘目录信息能麻烦发一下
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/51012725/294411515-15df4356-d133-4819-81d1-94317cbc2db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzY2NDQsIm5iZiI6MTcwNDQzNjM0NCwicGF0aCI6Ii81MTAxMjcyNS8yOTQ0MTE1MTUtMTVkZjQzNTYtZDEzMy00ODE5LTgxZDEtOTQzMTdjYmMyZGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWY2N2M2NWNmY2ZjNzVjMjE5ZTc3NjY0ZWY0YTNiZWEzYzFmZTQ5MGI0ZWU0NWQ0Njc4NjcxM2QzYTc5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.75L7v_YA24jq6BH7ocyUYT1LVh_c2xIQ5jEmGN9_GwQ)
> 
> 麻烦看下tmp和opt目录的使用情况，如果剩余空间比较小，建议清理掉一部分。安装时参数加上-b 0 不备份

tmp和opt两个目录文件不大。加-b 0不备份也安装失败
![image](https://github.com/flagify-com/OctoMation/assets/51012725/a5302b66-9271-4939-8e3d-df44c1ec6e95)
![image](https://github.com/flagify-com/OctoMation/assets/51012725/31a7e65b-b92e-4245-8c10-5abb3dc316b7)

**Comment by wuzhi-dev** [comment]
老师  麻烦看下tmp和opt的可用空间

**Comment by wuzhi-dev** [comment]
![image](https://github.com/flagify-com/OctoMation/assets/148321736/4092f12b-cfbe-420c-901e-79abce75235c)
用centos7.9，8g内存，200g硬盘，默认分区，非最小化安装（带gui的服务器），没有问题，是否可以远程看下

**Comment by wuzhi-dev** [comment]
echo -e "
source /etc/profile
echo $?
set -e
source /etc/profile
echo $?" > test.sh

bash test.sh


执行一下这段命令，看是否返回0，如果不是的话要检查一下profile是否有错误

**Comment by Belee05** [comment]
> echo -e "
> source /etc/profile
> echo $?
> set -e
> source /etc/profile
> echo $?" > test.sh
执行返回0
![image](https://github.com/flagify-com/OctoMation/assets/51012725/029b9e18-acdf-4c6f-a6aa-09f1482b0e44)

**Comment by xiaoyugo61** [comment]
test.sh中的 `echo 0` 请改为`echo $?`

**Comment by Belee05** [comment]
> test.sh中的 `echo 0` 请改为`echo $?`

一样是返回0
![image](https://github.com/flagify-com/OctoMation/assets/51012725/33167f5f-f1f5-40d5-8666-94e4e610ffb1)

**Comment by xiaoyugo61** [comment]
结果只打印了一个0，说明连续多次source，会报错，需要您排查一下

**Comment by Belee05** [comment]
> 结果只打印了一个0，说明连续多次source，会报错，需要您排查一下

是系统的/etc/profile有个`PS1`环境变量导致的，应该是跟脚本里面的环境变量有冲突，现在安装成功了，谢谢师傅
